apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  labels:
    app: rust-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: deluxe-aqua-idol-gradually.trycloudflare.com/rust-api:latest
        
        ports:
        - containerPort: 8080
        env:
        - name: GO_SERVICE_URL
          value: "http://go-api:8081"
        resources:
          requests:
            cpu: "10m"      # Bajamos de 50m/100m a solo 10m
            memory: "32Mi"  # Bajamos de 64Mi/128Mi a 32Mi
          limits:
            cpu: "100m"
            memory: "64Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: rust-api
  labels:
    app: rust-api
spec:
  selector:
    app: rust-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  
