apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: 068799688bed.ngrok-free.app/rust-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "300m"
