apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-proyecto
  namespace: backend
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /venta
        pathType: Prefix
        backend:
          service:
            name: rust-api
            port:
              number: 8080