apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  
  labels:
    app: go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api
        image: deluxe-aqua-idol-gradually.trycloudflare.com/go-api:latest   # cambia seg√∫n tu Zot
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: GRPC_SERVER_ADDR
          value: "go-server:50051"
        resources:
          requests:
            cpu: "10m"      # Bajamos de 50m/100m a solo 10m
            memory: "32Mi"  # Bajamos de 64Mi/128Mi a 32Mi
          limits:
            cpu: "100m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: go-api
  
  labels:
    app: go-api
spec:
  selector:
    app: go-api
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  
